#!/usr/bin/env bash
# Transfer a file from the client to a server

pathToFile="$1"
ipAddress="$2"
userName="$3"
sshKeyPath="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$sshKeyPath" "$pathToFile" "$userName"@"$ipAddress":~/
fi
