#!/usr/bin/env bash
# configure HAproxy

sudo sed -i 's/defaults/listen webs\n   bind :80\n   balance roundrobin\n   server 1661-web-01 54.235.58.144:80 check\n   server 1661-web-02 34.73.211.9:80 check\n\ndefaults/g' /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
