#!/usr/bin/env bash
# short and sweet
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
usermod -aG sudo nginx
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
